"""add ai_interpretation to assessment_session

Revision ID: a4d1d906ff46
Revises: 0003
Create Date: 2026-05-10 17:09:25.091038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4d1d906ff46'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_recommendations', 'rank',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.alter_column('assessment_recommendations', 'is_conflict',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('assessment_recommendations', 'created_at')
    op.alter_column('assessment_responses', 'answer',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.drop_column('assessment_responses', 'updated_at')
    op.drop_column('assessment_responses', 'created_at')
    op.add_column('assessment_sessions', sa.Column('ai_interpretation', sa.Text(), nullable=True))
    op.alter_column('assessment_sessions', 'algorithm_version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'v1'::character varying"))
    op.alter_column('assessment_sessions', 'score_r',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_i',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_a',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_s',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_e',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_c',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('interest_rounds', 'created_at')
    op.drop_index(op.f('ix_major_categories_assessment_code'), table_name='major_categories')
    op.create_index(op.f('ix_major_categories_assessment_category_code'), 'major_categories', ['assessment_category_code'], unique=False)
    op.drop_column('major_categories', 'created_at')
    op.alter_column('majors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('majors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('majors', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('majors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('major_categories', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_major_categories_assessment_category_code'), table_name='major_categories')
    op.create_index(op.f('ix_major_categories_assessment_code'), 'major_categories', ['assessment_category_code'], unique=False)
    op.add_column('interest_rounds', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('assessment_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessment_sessions', 'score_c',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_e',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_s',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_a',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_i',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'score_r',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('assessment_sessions', 'algorithm_version',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'v1'::character varying"))
    op.drop_column('assessment_sessions', 'ai_interpretation')
    op.add_column('assessment_responses', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('assessment_responses', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('assessment_responses', 'answer',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('assessment_recommendations', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('assessment_recommendations', 'is_conflict',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('assessment_recommendations', 'rank',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
