/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Start a new assessment session. Call this before showing the first question.
         */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Responses
         * @description Batch-save answers. Safe to call multiple times (upsert by question_id).
         *     Allows the frontend to persist progress incrementally.
         */
        post: operations["submit_responses_api_v1_sessions__session_id__responses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Session
         * @description Compute RIASEC scores and major recommendations, persist them, mark session completed.
         *     Idempotent: calling again on a completed session returns the cached result.
         */
        post: operations["complete_session_api_v1_sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Result
         * @description Retrieve results for a completed session (e.g. for share links).
         */
        get: operations["get_result_api_v1_sessions__session_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/majors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Majors
         * @description Return all active majors, optionally filtered by search term.
         */
        get: operations["list_majors_api_v1_majors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/majors/{major_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Major
         * @description Return a single major by ID.
         */
        get: operations["get_major_api_v1_majors__major_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssessmentResult
         * @description POST /sessions/{id}/complete 和 GET /sessions/{id}/result 的响应。
         */
        AssessmentResult: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            riasec_scores: components["schemas"]["RiasecScoresOut"];
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationItem"][];
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MajorDetail */
        MajorDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Discipline Category */
            discipline_category: string;
            /** Major Category */
            major_category: string;
            /** Description */
            description?: string | null;
            /** Riasec R */
            riasec_r: number;
            /** Riasec I */
            riasec_i: number;
            /** Riasec A */
            riasec_a: number;
            /** Riasec S */
            riasec_s: number;
            /** Riasec E */
            riasec_e: number;
            /** Riasec C */
            riasec_c: number;
        };
        /** MajorListResponse */
        MajorListResponse: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["MajorDetail"][];
        };
        /**
         * MajorSummary
         * @description 推荐结果里每个专业的简要信息，不暴露 RIASEC profile 等内部数据。
         */
        MajorSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Discipline Category */
            discipline_category: string;
            /** Major Category */
            major_category: string;
        };
        /**
         * RecommendationItem
         * @description 一条推荐记录：排名 + 相似度 + 专业简介。
         */
        RecommendationItem: {
            /** Rank */
            rank: number;
            /** Similarity Score */
            similarity_score: number;
            major: components["schemas"]["MajorSummary"];
        };
        /**
         * ResponseItem
         * @description 一道题的答案。
         */
        ResponseItem: {
            /** Question Id */
            question_id: string;
            /** Module */
            module: string;
            /** Answer */
            answer: number;
            /** Answered At */
            answered_at?: string | null;
        };
        /**
         * RiasecScoresOut
         * @description 六维 RIASEC 分数，0-100，返回给前端用于画雷达图。
         */
        RiasecScoresOut: {
            /** R */
            R: number;
            /** I */
            I: number;
            /** A */
            A: number;
            /** S */
            S: number;
            /** E */
            E: number;
            /** C */
            C: number;
            /** Dominant Type */
            dominant_type: string;
            /** Top Two */
            top_two: [
                string,
                string
            ];
        };
        /**
         * SessionCreated
         * @description POST /sessions 的响应：后端返回给前端的 session 编号。
         */
        SessionCreated: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Algorithm Version */
            algorithm_version: string;
        };
        /**
         * SubmitResponsesRequest
         * @description POST /sessions/{id}/responses 的请求体：打包提交多道题的答案。
         */
        SubmitResponsesRequest: {
            /** Responses */
            responses: components["schemas"]["ResponseItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
        };
    };
    submit_responses_api_v1_sessions__session_id__responses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitResponsesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_v1_sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_v1_sessions__session_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_majors_api_v1_majors_get: {
        parameters: {
            query?: {
                /** @description 按专业名称或学科类别模糊搜索 */
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MajorListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_major_api_v1_majors__major_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                major_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MajorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
